#ifndef TAGEDITOR_GLOBAL_H
#define TAGEDITOR_GLOBAL_H

#if defined(MIAMTAGEDITOR_LIBRARY)
#undef MIAMTAGEDITOR_LIBRARY
#define MIAMTAGEDITOR_LIBRARY Q_DECL_EXPORT
#else
#define MIAMTAGEDITOR_LIBRARY Q_DECL_IMPORT
#endif

#endif // TAGEDITOR_GLOBAL_H
