#ifndef LIBRARY_GLOBAL_H
#define LIBRARY_GLOBAL_H

#if defined(MIAMLIBRARY_LIBRARY)
#undef MIAMLIBRARY_LIBRARY
#define MIAMLIBRARY_LIBRARY Q_DECL_EXPORT
#else
#define MIAMLIBRARY_LIBRARY Q_DECL_IMPORT
#endif

#endif // LIBRARY_GLOBAL_H
