#ifndef ACOUSTID_GLOBAL_H
#define ACOUSTID_GLOBAL_H

#if defined(MIAMACOUSTID_LIBRARY)
#undef MIAMACOUSTID_LIBRARY
#define MIAMACOUSTID_LIBRARY Q_DECL_EXPORT
#else
#define MIAMACOUSTID_LIBRARY Q_DECL_IMPORT
#endif

#endif // ACOUSTID_GLOBAL_H
