#ifndef COVERFETCHER_GLOBAL_H
#define COVERFETCHER_GLOBAL_H

#if defined(MIAMCOVERFETCHER_LIBRARY)
#undef MIAMCOVERFETCHER_LIBRARY
#define MIAMCOVERFETCHER_LIBRARY Q_DECL_EXPORT
#else
#define MIAMCOVERFETCHER_LIBRARY Q_DECL_IMPORT
#endif

#endif // COVERFETCHER_GLOBAL_H
