#ifndef TABPLAYLISTS_GLOBAL_H
#define TABPLAYLISTS_GLOBAL_H

#if defined(MIAMTABPLAYLISTS_LIBRARY)
#undef MIAMTABPLAYLISTS_LIBRARY
#define MIAMTABPLAYLISTS_LIBRARY Q_DECL_EXPORT
#else
#define MIAMTABPLAYLISTS_LIBRARY Q_DECL_IMPORT
#endif

#endif // TABPLAYLISTS_GLOBAL_H
